DROP INDEX route_id_vp_idx;
DROP INDEX direction_id_vp_idx;
DROP INDEX journey_start_time_vp_idx;
DROP INDEX unique_vehicle_id_vp_idx;
DROP INDEX oday_vp_idx;
DROP INDEX lat_vp_idx;
DROP INDEX long_vp_idx;
DROP INDEX tsi_vp_idx;
DROP INDEX next_stop_vp_id_idx;
DROP INDEX stop_id_vp_idx;
DROP INDEX index10_vp;
DROP INDEX journey_type_vp_idx;
DROP INDEX event_type_vp_idx;ON vehicleposition (tst ASC, journey_type, unique_vehicle_id) ;
DROP INDEX area_search_vp_idx;
DROP INDEX route_departures_vp_idx;
DROP INDEX stop_departure_vp_idx;
DROP INDEX unsigned_events_vp_idx;

CREATE INDEX IF NOT EXISTS route_id_lp_idx ON lightpriorityevent (route_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS direction_id_lp_idx ON lightpriorityevent (direction_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS journey_staart_time_lp_idx ON lightpriorityevent (journey_start_time) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS unique_vehicle_id_lp_idx ON lightpriorityevent USING brin (unique_vehicle_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS oday_lp_idx ON lightpriorityevent USING brin (oday) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS lat_lp_idx ON lightpriorityevent (lat) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS long_lp_idx ON lightpriorityevent (long) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS tsi_lp_idx ON lightpriorityevent (tsi) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS next_lp_lpop_id_idx ON lightpriorityevent USING brin (next_stop_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS stop_lp_id_idx ON lightpriorityevent (stop) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS index10_lp ON lightpriorityevent (oday, geohash_level, unique_vehicle_id, vehicle_number, owner_operator_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS journey_type_lp_idx ON lightpriorityevent (journey_type) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS event_type_lp_idx ON lightpriorityevent (event_type) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS area_search_lp_idx ON lightpriorityevent (tst ASC, lat ASC, long ASC, journey_type, event_type) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS route_departures_lp_idx ON lightpriorityevent (event_type, oday, route_id, direction_id, stop, journey_start_time ASC, unique_vehicle_id ASC, tst DESC) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS stop_departure_lp_idx ON lightpriorityevent (event_type, oday, stop) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS unsigned_events_lp_idx ON lightpriorityevent (tst ASC, journey_type, unique_vehicle_id) WITH (timescaledb.transaction_per_chunk);

CREATE INDEX IF NOT EXISTS route_id_oe_idx ON otherevent (route_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS direction_id_oe_idx ON otherevent (direction_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS journey_start_time_oe_idx ON otherevent (journey_start_time) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS unique_vehicle_id_oe_idx ON otherevent USING brin (unique_vehicle_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS oday_oe_idx ON otherevent USING brin (oday) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS lat_oe_idx ON otherevent (lat) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS long_oe_idx ON otherevent (long) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS tsi_oe_idx ON otherevent (tsi) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS next_oe_stop_id_idx ON otherevent USING brin (next_stop_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS stop_oe_id_idx ON otherevent (stop) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS index10_oe ON otherevent (oday, geohash_level, unique_vehicle_id, vehicle_number, owner_operator_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS journey_type_oe_idx ON otherevent (journey_type) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS event_type_oe_idx ON otherevent (event_type) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS area_search_oe_idx ON otherevent (tst ASC, lat ASC, long ASC, journey_type, event_type) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS route_departures_oe_idx ON otherevent (event_type, oday, route_id, direction_id, stop, journey_start_time ASC, unique_vehicle_id ASC, tst DESC) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS stop_departure_oe_idx ON otherevent (event_type, oday, stop) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS unsigned_events_oe_idx ON otherevent (tst ASC, journey_type, unique_vehicle_id) WITH (timescaledb.transaction_per_chunk);

CREATE INDEX IF NOT EXISTS route_id_st_idx ON stopevent (route_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS direction_id_st_idx ON stopevent (direction_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS journey_start_time_st_idx ON stopevent (journey_start_time) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS unique_vehicle_id_st_idx ON stopevent USING brin (unique_vehicle_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS oday_st_idx ON stopevent USING brin (oday) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS lat_st_idx ON stopevent (lat) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS long_st_idx ON stopevent (long) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS tsi_st_idx ON stopevent (tsi) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS next_st_stop_id_idx ON stopevent USING brin (next_stop_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS stop_st_id_idx ON stopevent (stop) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS index10_st ON stopevent (oday, geohash_level, unique_vehicle_id, vehicle_number, owner_operator_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS journey_type_st_idx ON stopevent (journey_type) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS event_type_st_idx ON stopevent (event_type) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS area_search_st_idx ON stopevent (tst ASC, lat ASC, long ASC, journey_type, event_type) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS route_departures_st_idx ON stopevent (event_type, oday, route_id, direction_id, stop, journey_start_time ASC, unique_vehicle_id ASC, tst DESC) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS stop_departure_st_idx ON stopevent (event_type, oday, stop) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS unsigned_events_st_idx ON stopevent (tst ASC, journey_type, unique_vehicle_id) WITH (timescaledb.transaction_per_chunk);

CREATE INDEX IF NOT EXISTS route_id_ue_idx ON unsignedevent (route_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS direction_id_ue_idx ON unsignedevent (direction_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS journey_start_time_ue_idx ON unsignedevent (journey_start_time) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS unique_vehicle_id_ue_idx ON unsignedevent USING brin (unique_vehicle_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS oday_ue_idx ON unsignedevent USING brin (oday) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS lat_ue_idx ON unsignedevent (lat) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS long_ue_idx ON unsignedevent (long) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS tsi_ue_idx ON unsignedevent (tsi) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS next_ue_stop_id_idx ON unsignedevent USING brin (next_stop_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS stop_ue_id_idx ON unsignedevent (stop) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS index10_ue ON unsignedevent (oday, geohash_level, unique_vehicle_id, vehicle_number, owner_operator_id) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS journey_type_ue_idx ON unsignedevent (journey_type) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS event_type_ue_idx ON unsignedevent (event_type) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS area_search_ue_idx ON unsignedevent (tst ASC, lat ASC, long ASC, journey_type, event_type) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS route_departures_ue_idx ON unsignedevent (event_type, oday, route_id, direction_id, stop, journey_start_time ASC, unique_vehicle_id ASC, tst DESC) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS stop_departure_ue_idx ON unsignedevent (event_type, oday, stop) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX IF NOT EXISTS unsigned_events_ue_idx ON unsignedevent (tst ASC, journey_type, unique_vehicle_id) WITH (timescaledb.transaction_per_chunk);